Update documentation to SDK v1.0(244)
Vualto/vudrm-public-docs pull request #62
Opened 2020-10-14 11:23 UTC by macmagician

Merge iOS and tvOS into one document to reflect shared source.

2020-10-14 12:00 UTC, fschurer requested changes

2020-10-14 12:12 UTC, rogerpales approved these changes

2020-10-14 12:47 UTC, macmagician commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> +The demo application that we use targets both iOS and tvOS platforms using shared source code. Each target platform references it's own version of the framework.
resolved commit a1fa0558f5a9887d2f38a9660840e7e7c0a36506

2020-10-14 12:48 UTC, macmagician commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> +- The `is_protected` boolean value indicates whether the content is protected with DRM or not. This value can be overrideen in source if all content is protected.
resolved commit a1fa0558f5a9887d2f38a9660840e7e7c0a36506

2020-10-14 15:32 UTC, fschurer approved these changes

2020-10-14 16:35 UTC, PerritonBranch requested changes

2020-10-14 16:35 UTC, PerritonBranch commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> +With the VUDRMFairPlay framework installed, the example demo application reads entries in the `Streams.plist` file to configure the content and DRM. You can edit the `Streams.plist` file values, and/
```suggestion
With the VUDRMFairPlay framework installed, the example demo application reads entries in the `Streams.plist` file to configure the content and DRM. You can edit the `Streams.plist` file values, and/or add your own valid values, which should include a `content_id`, `playlist_url`, and `vudrm_token`(see [Preparation](#preparation) above).
```

2020-10-14 16:35 UTC, PerritonBranch commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> +Requests for playback or download will request a license for the content from the license server based on the type of token presented for each instance of VUDRMFairPlay. The tokens may be FairPlay Re
```suggestion
Requests for playback or download will result in a license request for the content from the license server, based on the type of token presented for each instance of VUDRMFairPlay. The tokens may be FairPlay Rental or FairPlay Persist. FairPlay Rental token license requests will be provided a streaming content key, which may be used for online streaming only. FairPlay Persist token license requests will be provided a persistent content key, which may be used for both online streaming, and offline playback of downloaded content.
```

2020-10-16 15:38 UTC, macmagician commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> + - A `name` for the content. This will be the readable display name and is not used by the SDK. This may differ from the `contentID`.
resolved commit: facdd5bc708bdf51abc20cd1dda702e8531327c3

2020-10-16 15:39 UTC, macmagician commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> + - A `content_id` for the content, being the same content ID that the content was prpeared with. This value will always be the last path component of the stream `content_key_id_list` or `skd://` URI
resolved commit: facdd5bc708bdf51abc20cd1dda702e8531327c3

2020-10-16 15:42 UTC, fschurer submitted a review, later dismissed

2020-10-16 16:16 UTC, PerritonBranch requested changes

2020-10-16 16:16 UTC, PerritonBranch commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> +There are significant limitations using AirPlay to stream any content to an Apple TV that has been downloaded to the users device. Please see the [Limitations]((#limitations)) section for further inf
```suggestion
There are significant limitations using AirPlay to stream any content to an Apple TV that has been downloaded to the users device. Please see the [Limitations](#limitations) section for further information.
```

2020-10-16 16:26 UTC, PerritonBranch approved these changes

2020-10-16 16:36 UTC, fschurer approved these changes

2020-10-19 08:27 UTC, merged