Add docs on how to block vpns and tor networks using a tokens policy.
Vualto/vudrm-public-docs pull request #64
Opened 2020-10-21 10:06 UTC by PerritonBranch

2020-10-21 15:59 UTC, fschurer approved these changes

2020-10-22 16:29 UTC, somerobmitchell submitted a review, later dismissed

2020-10-22 16:29 UTC, somerobmitchell commented
waiting for https://github.com/Vualto/vudrm-kp-api/pull/26 to be merged and released.

2020-10-22 16:30 UTC, rogerpales approved these changes

2020-10-23 15:29 UTC, fschurer requested changes

2020-10-23 15:29 UTC, fschurer commented on docs/source/VUDRM-token.md
> +| `block_vpn_and_tor` | bool    | `ture` or `false`         | ALL   | Boolean for if ips coming from known vpn or tor networks should be blocked. |
Typo ('ture' should be 'true')

2020-11-09 17:24 UTC, fschurer approved these changes

2020-11-12 22:43 UTC, rogerpales approved these changes

2020-11-18 17:28 UTC, merged