Update iOS/tvOS SDK documentation to SDK v1.0(254/255)
Vualto/vudrm-public-docs pull request #68
Opened 2020-12-07 10:35 UTC by macmagician

Add Troubleshooting

2020-12-08 11:09 UTC, PerritonBranch requested changes

2020-12-08 11:09 UTC, PerritonBranch commented on docs/source/integrations/mobile/ios-fairplay-sdk.md
> +	- Tokens - You can easily eliminate token issues by beginning with a default FairPlay token policy. Please ensure your token is formatted correctly and validates. For the avoidance of doubt, where t
```suggestion
	- Tokens - You can easily eliminate token issues by beginning with a default FairPlay token policy. Please ensure your token is formatted correctly and validates. For the avoidance of doubt, where tokens use dates, the dates should always be in the future. For further information about tokens please refer to our token [documentation](https://docs.vualto.com/projects/vudrm/en/latest/VUDRM-token.html).
```

2020-12-08 11:37 UTC, PerritonBranch approved these changes

2020-12-09 16:21 UTC, fschurer approved these changes

2020-12-09 16:22 UTC, merged