Update documentation for AndroidX and Exoplayer 12
Vualto/vudrm-public-docs pull request #69
Opened 2020-12-10 15:23 UTC by macmagician

2020-12-10 16:32 UTC, PerritonBranch requested changes

2020-12-10 16:32 UTC, PerritonBranch commented on docs/source/integrations/mobile/android-widevine-sdk.md
> +	- Tokens - You can easily eliminate token issues by beginning with a default Widevine token policy. Please ensure your token is formatted correctly and validates. For the avoidance of doubt, where t
```suggestion
	- Tokens - You can easily eliminate token issues by beginning with an empty policy in the VUDRM token. Please ensure your token is formatted correctly and validates. For the avoidance of doubt, where tokens use dates, the dates should always be in the future. For further information about tokens please refer to our [documentation](https://docs.vualto.com/projects/vudrm/en/latest/VUDRM-token.html).
```

2020-12-10 17:44 UTC, fschurer approved these changes

2020-12-14 09:35 UTC, PerritonBranch approved these changes

2020-12-14 09:38 UTC, merged