Added info about can_renew in token policy.
Vualto/vudrm-public-docs pull request #76
Opened 2021-03-19 13:52 UTC by PerritonBranch

2021-03-19 16:46 UTC, fschurer requested changes

2021-03-19 16:46 UTC, fschurer commented on docs/source/DeveloperDocumentation/VUDRM-token.md
> +To enable automatic license renewal `can_renew` must be set to true; you must also have set `polend` to be more than 60 seconds in the future or have set `duration_persist` to be more than 60. If thi
Could we change 'if this criteria is met' to 'if these criteria are met... etc'?
Also, the should latter half of the sentence say 'a request will be made automatically'?

2021-03-22 11:53 UTC, fschurer approved these changes

2021-03-24 07:31 UTC, rogerpales approved these changes

2021-05-13 14:28 UTC, merged