Added information about ISO 8601 format for times.
Vualto/vudrm-public-docs pull request #77
Opened 2021-03-19 15:18 UTC by PerritonBranch

2021-03-19 16:33 UTC, fschurer approved these changes

2021-03-24 07:31 UTC, rogerpales requested changes

2021-03-24 07:31 UTC, rogerpales commented on docs/source/DeveloperDocumentation/VUDRM-token.md
> +| `polbegin`         | datetime | ISO 8601 or DD-MM-YYYY HH:mm:ss      | ALL            | **The non ISO 8601 format is no longer recommended, please use the ISO 8601 format.** Policy Begin. The start
typo in specified, here and below

2021-03-24 10:56 UTC, rogerpales approved these changes

2021-03-24 11:00 UTC, fschurer approved these changes

2021-04-07 16:06 UTC, merged