Origin/ios fairplaysdk update
Vualto/vudrm-public-docs pull request #78
Opened 2021-06-22 12:24 UTC by macmagician

2021-06-22 16:31 UTC, PerritonBranch requested changes

2021-06-22 16:31 UTC, PerritonBranch commented on docs/source/DeveloperDocumentation/integrations/mobile/ios-tvos-vudrmfairplaysdk.md
> +For further information about VUDRM please contact us, or refer to our documentation:
```suggestion
For further information about VUDRM please contact us, or refer to our [documentation](https://docs.vualto.com/projects/vudrm/en/latest/VUDRM-token.html).
```

2021-06-22 16:31 UTC, PerritonBranch commented on docs/source/DeveloperDocumentation/integrations/mobile/ios-tvos-vudrmfairplaysdk.md
> +If you are not able to play your content after checking it in our demo application please contact support@vualto.com with the demo application logs and the stream configuration used.
```suggestion
If you are not able to play your content after checking it in our demo application please contact [support@vualto.com](support@vualto.com) with the demo application logs and the stream configuration used.
```

2021-06-25 12:46 UTC, fschurer approved these changes

2021-06-28 16:00 UTC, PerritonBranch approved these changes

2021-06-28 16:00 UTC, merged